text_data = {
    'ES': {
        'title': "Buscador de números faltantes",
        'idioma': "Idioma",
        'prefijo': "Prefijo (opcional):",
        'inicio': "Valor inicial:",
        'fin': "Valor final:",
        'repeticiones': "Repeticiones:",
        'buscar_texto': "Buscar en Texto",
        'buscar_archivo': "Buscar en Archivo",
        'copiar': "Copiar resultados",
        'vacio_title': "Vacío",
        'vacio_msg': "No hay texto para analizar.",
        'error_title': "Error",
        'error_datos_msg': "Ingresaste mal los datos: El valor inicial, final y de repeticiones deben ser números enteros",
        'faltantes_msg': "Se encontraron {cantidad} números faltantes:\n\n",
        'menos_rep_msg': "Se encontraron {cantidad} números con menos de {repeticiones} repeticiones:\n\n",
        'perfecto_msg': "No faltan números en la secuencia.",
        'select_file_title': "Seleccionar archivo",
        'text_files': "Archivos de texto",
        'file_error_title': "Error de Archivo",
        'file_error_msg': "No se pudo leer el archivo:\n{e}",
        'copiado_title': "Copiado",
        'copiado_msg': "Resultados copiados al portapapeles"
    },
    'EN': {
        'title': "Missing Number Finder",
        'idioma': "Language",
        'prefijo': "Prefix (optional):",
        'inicio': "Start value:",
        'fin': "End value:",
        'repeticiones': "Repetitions:",
        'buscar_texto': "Search in Text",
        'buscar_archivo': "Search in File",
        'copiar': "Copy Results",
        'vacio_title': "Empty",
        'vacio_msg': "No text to analyze.",
        'error_title': "Error",
        'error_datos_msg': "Invalid data: Start, end, and repetition values must be integers.",
        'faltantes_msg': "Found {cantidad} missing numbers:\n\n",
        'menos_rep_msg': "Found {cantidad} numbers with less than {repeticiones} repetitions:\n\n",
        'perfecto_msg': "No missing numbers.",
        'select_file_title': "Select file",
        'text_files': "Text files",
        'file_error_title': "File Error",
        'file_error_msg': "Could not read file:\n{e}",
        'copiado_title': "Copied",
        'copiado_msg': "Results copied to clipboard"
    }
}